# Generated by Django 4.2.8 on 2023-12-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sign_up', models.DateTimeField(auto_created=True)),
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=40, unique=True)),
                ('user_password', models.CharField(max_length=100)),
                ('user_hp', models.CharField(max_length=11)),
            ],
        ),
    ]
