# Generated by Django 4.2.8 on 2023-12-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('type_idx', models.IntegerField()),
                ('instructor', models.CharField(max_length=40)),
                ('classroom', models.CharField(max_length=100)),
                ('lesson_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LessonInfo',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='sign_up',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
