# Generated by Django 4.2.8 on 2023-12-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_lesson_lessoninfo_alter_student_sign_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='max_attend',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lessoninfo',
            name='type_price',
            field=models.IntegerField(default=0),
        ),
    ]
