# Generated by Django 4.2.8 on 2023-12-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_lesson_max_attend_lessoninfo_type_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_at',
            field=models.DateTimeField(),
        ),
    ]
